### ISSUE TITLE
소개란에 들어갈 문구 선정이 필요합니다.

### ISSUE THREAD

**Issue by sang-hyeon** [dotnetdev-kr/DotNetConf2022_LandingPage#1]
소개란에 표시될 문구 선정이 필요합니다.

## Screen
https://dotnetdev-kr.github.io/DotNetConf2022_LandingPage/#about-section

## 논의 해야할 문구 주제

" .NET Conf 2022 x Seoul에 함께 하셔야 하는 이유 "

## 생각되는 후보들

1. 풀스택으로 사용될 수 있는 .NET을 확인할 수 있습니다. 
2. 국내 최대 .NET 컨퍼런스입니다.
3. .NET이 지원하는 최신 기술을 확인할 수 있습니다.
4. ....?

## 기타 논의
'.NET Conf 2022 x Seoul에 함께 하셔야 하는 이유' 말고 다른 이야기가 있을지...

기입될만한 문구를 이 이슈에서 공유해주세요.

**Comment by rkttu** [comment]
함께 해야 할 이유라는 워딩은 템플릿을 그대로 직역한 것 같은 느낌이라 좀 어색한데요, "이번 컨퍼런스에서 다루는 내용"으로 워딩을 바꿔서 아이디어를 모아본다면 어떨까요?

**Comment by level120** [comment]
이번 컨퍼런스에서 다루는 대분류 주제로 쓰는 것은 어떨까요?
notion에 있었던 아래 내용처럼요

- 트랙 1: [ASP.NET](http://asp.net/), 웹 프론트엔드 (Blazor)
- 트랙 2: 데스크톱, 모바일 (MAUI), 게임 (Unity)
- 트랙 3: 클라우드, DevOps, 머신러닝, 빅데이터, AI
- 트랙 4: 프로그래밍 언어 (C#, [VB.NET](http://vb.net/), ...)

**Comment by sang-hyeon** [comment]
> 이번 컨퍼런스에서 다루는 대분류 주제로 쓰는 것은 어떨까요? notion에 있었던 아래 내용처럼요
> 
> * 트랙 1: [ASP.NET](http://asp.net/), 웹 프론트엔드 (Blazor)
> * 트랙 2: 데스크톱, 모바일 (MAUI), 게임 (Unity)
> * 트랙 3: 클라우드, DevOps, 머신러닝, 빅데이터, AI
> * 트랙 4: 프로그래밍 언어 (C#, [VB.NET](http://vb.net/), ...)

오호, 이 아이디어 좋은데 어떻게 보시나요? @rkttu 

제목을 '이번 컨퍼런스에서 다루는 내용' 으로 교체하고, 위에 @level120 님이 언급하신 트랙을 나열하는게 좋을 것 같은 생각입니다.

**Comment by rkttu** [comment]
제가 답이 늦었네요 🙏 
동의합니다.
