### ISSUE TITLE
페이지에서 전체 스피커분들 나열에 대해서...

### ISSUE THREAD

**Issue by sang-hyeon** [dotnetdev-kr/DotNetConf2022_LandingPage#2]
페이지에서 전체 스피커분들을 나열하기에 인원이 꽤 되는거 같은 느낌이 드는데... 문제가 없을지 궁금합니다.

그렇다고 대표적인 몇분만 표시하기엔 조금 어려운면이 있는거 같습니다. (차별하는거 같아보이니...)

## Screen
https://dotnetdev-kr.github.io/DotNetConf2022_LandingPage/#speakers-section

## 의견
개인적인 생각으로는 스크롤이 길어지더라도 모든 분들을 표시하는게 좋겠다는 생각입니다.

**Comment by rkttu** [comment]
코딩이 조금 필요할 것 같은데, 데이터 소스를 별도 json으로 만들어놓고 페이지 새로 고침때 마다 랜덤 표시하도록 하는 방법을 생각할 수 있을 것 같아요!

**Comment by sang-hyeon** [comment]
> 코딩이 조금 필요할 것 같은데, 데이터 소스를 별도 json으로 만들어놓고 페이지 새로 고침때 마다 랜덤 표시하도록 하는 방법을 생각할 수 있을 것 같아요!

랜덤으로 표시 하는건 아주 좋은 생각인거 같습니다. (공평하니...)
며칠간 다른 의견이 제안되지 않는다면 전체 인원을 랜덤하게 쭉 나열하겠습니다.
