### ISSUE TITLE
참가 신청 속 '무엇이 포함됩니까?' 에 대하여

### ISSUE THREAD

**Issue by sang-hyeon** [dotnetdev-kr/DotNetConf2022_LandingPage#3]
참가 신청 속 '무엇이 포함됩니까?' 란이 존재하는데 저희에게 필요할지 논의가 필요합니다.

## Screen
https://dotnetdev-kr.github.io/DotNetConf2022_LandingPage/#tickets-section

## 존재하는 이유
이전에는 '참가 신청'하면 어떠한 혜택을 받게되는지 소개하기위해 사용되었습니다.

## 기타
만약 그대로 둔다면 사은품과 같은 혜택에 대해 열거해야할 듯합니다.

**Comment by rkttu** [comment]
이 템플릿 자체가 규모가 큰 행사용으로 디자인된 것이다보니 우리 행사에는 맞지 않는 부분이 있어서, 제거해도 크게 허전하지 않다면 제거하는게 더 나을 것 같다는 의견입니다.

**Comment by sang-hyeon** [comment]
@rkttu 제 생각도 동일합니다.
며칠간 특별한 의견이 제안되지 않는다면 제거하는쪽으로 진행하겠습니다.

**Comment by level120** [comment]
![image](https://user-images.githubusercontent.com/10791961/142860187-c12229d3-e334-486b-a890-a7aae0f95113.png)

이쪽에 아래 사진처럼 닷넷데브 행사 유투브 스트리밍 프레임을 넣는 것은 어떨까요?
참가신청이 사라지고 이 자리에 스트리밍 프레임을 삽입하는 것 입니다.
스트리밍 주소가 잡히기 전까지는 유투브 프레임만 우선 달아놓아도 괜찮을 것 같아요.

![image](https://user-images.githubusercontent.com/10791961/142860287-46ba04c5-ed3d-42fb-8c65-3afbab924b02.png)
