### ISSUE TITLE
스케쥴 쪽 문구변경 건의

### ISSUE THREAD

**Issue by level120** [dotnetdev-kr/DotNetConf2022_LandingPage#4]
![image](https://user-images.githubusercontent.com/10791961/142859487-b29126e2-d8e3-4abc-9495-51147b166458.png)

이 사진에서 두 가지 건의사항이 있습니다.

1. 스케쥴 -> 일정
2. 당일 -> (당일을 제거하고 밑에 1월 28일이 위로)

이렇게 바꾸는 것은 어떨까요?
다른 소제목들이 다 한글인데 이쪽만 영어라서 좀 어색한 느낌이 있는 것 같아요.

그리고 2번은 행사가 2-3일 나눠있지 않는 한 1일차, 2일차를 표시하는 것보다 빼는게 더 좋을 것 같아서 건의드립니다.

**Comment by sang-hyeon** [comment]
@level120 

2번에 해당하는 의견입니다.

저는 개인적으로 저런 형식으로 '당일'을 쓰는게 괜찮다는 생각입니다.
이게 디자인적으로 날짜만 써있으면 좀 심심한 느낌이 있는거 같아서요.
다른분들 의견도 기다려보죠 ㅎ

**Comment by rkttu** [comment]
저도 동의합니다.

**Comment by level120** [comment]
@sang-hyeon 아 그럴수도 있겠네요, 제가 그쪽 관점에서 바라보지 않은 것 같아요.. 2번은 취소하는 것으로...
