### ISSUE TITLE
최상단 이미지 결정

### ISSUE THREAD

**Issue by rkttu** [dotnetdev-kr/DotNetConf2022_LandingPage#5]
페이지 최상단에 들어갈 이미지 결정

**Comment by rkttu** [comment]
@level120 님의 의견 - https://krdotnet.slack.com/archives/GUF922P54/p1637582941090400?thread_ts=1637576782.085100&cid=GUF922P54

```
방금 든 생각인데 저 첫장 이미지를 저희 랜딩 페이지에서 사용하는 것은 어떨까요?
꽤 이쁜데다 일관성있어 좋을 것 같아요.
물론 문구는 웹에서 지금 사용하고 있는 것을 그대로 활용하고 저 보라색 배경과 이미지, 그리고 닷넷데브 로고까지만 이미지로 만들어서요
```

**Comment by sang-hyeon** [comment]
@rkttu @level120 
이미지를 살짝 확인해봤는데...
이미지 자체의 주요 중심부(?) 라고 할 수 있는 하트 모양 주변에 여백이 없어서 사용에 어려움이 있지 않을까 사료됩니다.

최상단 이미지는 좌우로 와이드하게 뽑아 넣어야하는데, 아무리 편집해도 하트가 중앙에서 너무 확대 되는 것 같습니다.

[원본 이미지](https://unsplash.com/photos/I4dR572y7l0)

**Comment by sang-hyeon** [comment]
이미지를 제가 몇개 추려보았습니다. 투표해주세요.

1. https://unsplash.com/photos/uf2nnANWa8Q
2. https://unsplash.com/photos/F2KRf_QfCqw
3. https://unsplash.com/photos/Y9mWkERHYCU
4. 닷넷콘 2019에서 촬영한 실제 사진 (상준님 의견)

이외 다른 이미지를 희망하신다면 알려주세요.
후보에 추가하도록 하겠습니다.

**Comment by sang-hyeon** [comment]
1번.

**Comment by dimohy** [comment]
4번

**Comment by dimohy** [comment]
4번의 사진 퀄리티가 나쁠 경우 2번

**Comment by level120** [comment]
4 또는 1번

**Comment by sang-hyeon** [comment]
여기까지.

1번 : 2표
2번 : 1표
3번 : 0표
4번 : 2표 

나머지 분들 아래 투표 댓글 부탁드려요!

**Comment by rkttu** [comment]
우선 4번은 사진을 찾아봐야 해서, 가장 많은 득표를 얻은 1번 사진 시안을 사용하기로 미팅에서 결정하였습니다!
