### ISSUE TITLE
Hero 이미지 여백 남음

### ISSUE THREAD

**Issue by rkttu** [dotnetdev-kr/DotNetConf2022_LandingPage#7]
![image](https://user-images.githubusercontent.com/1297346/143687778-95809ab5-af3c-4c6c-8be6-16f7bcdb0ce5.png)

위의 그림과 같이 Hero 이미지가 해상도에 따라서는 좌/우의 여백이 남도록 표시되어 보기 좋지 않음. 이미지를 좀 더 큰 것을 쓰거나, 디자인적으로 보충할 방법을 고민해볼 필요가 있을 듯!

**Comment by sang-hyeon** [comment]
**현재 상태**
#5 에 의해 이미지가 변경되어 새로운 이미지에 대한 확인이 필요합니다.
