### ISSUE TITLE
festa.io 이벤트 접수 페이지 오픈 및 연결하기

### ISSUE THREAD

**Issue by rkttu** [dotnetdev-kr/DotNetConf2022_LandingPage#8]
festa.io 이벤트 접수 페이지를 등록하고 랜딩 페이지에 연결한다.

**Comment by sang-hyeon** [comment]
이게 랜딩 페이지 속 `참가 신청` 과 연결되는걸 말하는거죠?

**Comment by rkttu** [comment]
넵. 맞습니다. 그리고 https://festa.io/events/2020 페이지를 오픈했습니다.

**Comment by sang-hyeon** [comment]
@rkttu 페스타 링크를 행사 페이지속 '참가 신청'에 연결했는데 더 해야할게 있을까요?

**Comment by rkttu** [comment]
지금은 특별히 생각나는건 없습니다. 변동사항은 festa를 고치면 전달이 잘 될것같습니다.
